disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - trailing_newline
  
opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_parameters
  - vertical_whitespace_closing_braces
  
excluded:
  - Pods
  - .build
  - DerivedData
  - fastlane
  
line_length:
  warning: 150
  error: 180
  
function_body_length:
  warning: 100
  error: 120

file_length:
  warning: 568
  error: 700

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 25
  error: 40

included: # paths to include during linting
  - "*.swift"
  - "**/*.swift"
  - Controllers
  - Views
  - Models

excluded: # paths to ignore during linting
  - Preview Content
  - iconinkTests
  - iconinkUITests
  - Pods
  - "**/*.generated.swift"
  - .build

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y
    - db
    - i
    - at

force_cast: warning # implicitly
force_try: warning # explicitly

reporter: "xcode" # reporter type (json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)